version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "nest"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - test
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: "nest"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - test
networks:
  test: